### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ldlshizhu** [swz30/MPRNet#24]
Excuse me, what is the subdirectory' input' under' train' of deblur data set? Have you processed the gopro data set yourself? Because the subdirectory under the original gopro is ’gopro _ large/train/**（e.g gopr0884 _ 11 _ 00 )/sharp’
I don't know how to modify the path of dataset……
thank you very much!

**Comment by adityac8** [comment]
Hi @ldlshizhu 

We have downloaded the original dataset from [here](https://seungjunnah.github.io/Datasets/gopro) and re-organized the images from `GOPR0884_11_00/000285.png` to `GOPR0884_11_00-000285.png` so that all the images are in a single directory. The `input` directory contains blur images and `target` directory contains sharp images.

Thanks

**Comment by ldlshizhu** [comment]
oh I see! Could you please provide the processed dataset？I will be extremely grateful.

**Comment by adityac8** [comment]
The datasets are available here https://github.com/swz30/MPRNet/tree/main/Deblurring/Datasets
